In [5]:
import numpy as np

In [6]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.89222246, 0.43550414, 0.22630787, 0.61633294, 0.18542203])

In [59]:
np.random.rand(5,5)

array([[0.63273096, 0.13549936, 0.68654925, 0.85047357, 0.86076908],
       [0.08865707, 0.04074816, 0.63030599, 0.45200605, 0.90471425],
       [0.13204265, 0.23331882, 0.86303925, 0.89370141, 0.89843446],
       [0.78546505, 0.96442426, 0.40426497, 0.68940332, 0.36085716],
       [0.45924674, 0.71129919, 0.71859166, 0.66986795, 0.02487589]])

In [60]:
np.random.randn(4,4)

array([[-1.55315719, -0.62165295, -0.52423486,  1.47787659],
       [-0.43372442,  0.47021066, -0.28407379, -0.01744583],
       [-0.32154056,  1.00780855,  0.84100646, -1.57585841],
       [ 0.97329472, -0.2217233 ,  1.00598866, -0.03149841]])

In [61]:
np.random.randint(1,100)

38

In [62]:
np.random.randint(1,100,10)

array([65,  1, 19, 97, 94, 65,  7, 98,  2, 39])

In [67]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
arr = np.random.randint(1,50,10)
arr

array([44, 14, 43, 15, 36, 24, 10, 19, 42, 28])

In [70]:
arr.max()

44

In [71]:
arr.min()

10

In [72]:
arr

array([44, 14, 43, 15, 36, 24, 10, 19, 42, 28])

In [73]:
arr.argmax()

0

In [74]:
arr.argmin()

6

In [76]:
arr.shape

(10,)

In [79]:
rarr = np.arange(25)
rarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [84]:
rarr = rarr.reshape(5,5)
rarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
rarr.shape

(5, 5)

In [86]:
rarr.dtype

dtype('int32')